#!/usr/bin/env python3
"""PaperAudit static style linter.

This linter reports observable prose patterns. It does NOT detect AI authorship
and does NOT estimate whether text was generated by AI.

Standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

VERSION = "1.0.0"


@dataclass
class Finding:
    rule: str
    severity: str
    line: int
    excerpt: str
    message: str


# Deliberately narrow patterns. The goal is to identify review candidates, not
# maximize recall.
PATTERNS = [
    (
        "contrast.not_but",
        re.compile(r"\bnot\s+(?:merely\s+|simply\s+|only\s+)?[^.!?;]{1,100}\bbut\b", re.I),
        "low",
        "Contrastive 'not X but Y' structure; usually acceptable in isolation, but review if repeated or rhetorically unnecessary.",
    ),
    (
        "pivot.generic",
        re.compile(
            r"\b(?:this\s+(?:highlights|reveals|underscores|demonstrates|illustrates|points\s+to)|"
            r"what\s+matters\s+is|the\s+key\s+point\s+is|more\s+broadly)\b",
            re.I,
        ),
        "low",
        "Generic significance pivot; usually acceptable in isolation, but review repeated or weakly grounded use.",
    ),
    (
        "pivot.evidence_summary",
        re.compile(
            r"\b(?:this\s+(?:finding|sequence|case|pattern)\s+(?:demonstrates|shows|illustrates|highlights|reveals|underscores))\b",
            re.I,
        ),
        "low",
        "Evidence-summary pivot; keep when the following claim is study-specific, but review repeated formulaic use.",
    ),
    (
        "relevance.beyond",
        re.compile(r"\b(?:this|the)\s+(?:pattern|case|finding)s?\s+(?:has|have)\s+relevance\s+beyond\b", re.I),
        "low",
        "Beyond-case relevance claim; retain only when the wider relevance is specified rather than asserted.",
    ),
    (
        "signpost.emphasis",
        re.compile(r"\b(?:it\s+is\s+(?:important|worth)\s+to\s+note\s+that|crucially|importantly|notably)\b", re.I),
        "low",
        "Emphasis signpost; review if the claim can carry its own emphasis.",
    ),
    (
        "abstract.generic",
        re.compile(
            r"\b(?:broader\s+implications?|complex\s+interplay|multifaceted\s+nature|dynamic\s+landscape|"
            r"important\s+role|critical\s+importance|nuanced\s+understanding|wider\s+transformation)\b",
            re.I,
        ),
        "moderate",
        "Generic abstract phrase; specify the mechanism, entities, or implication if possible.",
    ),
]

PROTECTED_OPENINGS = [
    re.compile(r"^\s*this\s+study\s+(?:examines|investigates|analyses|analyzes|explores)\b", re.I),
    re.compile(r"^\s*this\s+paper\s+(?:argues|examines|investigates|analyses|analyzes)\b", re.I),
    re.compile(r"^\s*(?:the\s+)?findings\s+suggest\b", re.I),
    re.compile(r"^\s*previous\s+research\s+has\s+shown\b", re.I),
    re.compile(r"^\s*a\s+limitation\s+of\s+this\s+study\s+is\b", re.I),
]

GENERIC_CLOSURES = re.compile(
    r"\b(?:this\s+(?:highlights|underscores|reveals)\s+the\s+(?:importance|need)|"
    r"these\s+findings\s+have\s+broader\s+implications|this\s+points\s+to\s+the\s+need)\b",
    re.I,
)

# Conceptual papers often need explicit distinctions. These openings are not
# problematic by themselves; PaperAudit tracks their local density instead.
META_PIVOT = re.compile(
    r"^\s*(?:"
    r"the\s+important\s+point\s+is|"
    r"the\s+point\s+is|"
    r"the\s+relevant\s+question\s+is|"
    r"the\s+question\s+is|"
    r"the\s+more\s+relevant\s+questions\s+are|"
    r"the\s+contribution(?:\s+of\s+this\s+paper)?\s+is|"
    r"the\s+issue\s+is|"
    r"the\s+matrix\s+is|"
    r"the\s+important\s+requirement\s+is|"
    r"the\s+programme-level\s+implication\s+is|"
    r"the\s+program-level\s+implication\s+is|"
    r"the\s+distinction\s+(?:therefore\s+)?matters|"
    r"a\s+further\s+question\s+therefore\s+remains"
    r")\b",
    re.I,
)

NEGATIVE_REDEFINITION = re.compile(
    r"\b(?:is|are|does|do|did|should|must|can|cannot|could|would)\s+(?:therefore\s+)?not\b",
    re.I,
)

POSITIVE_REDEFINITION_OPENING = re.compile(
    r"^\s*(?:it\s+(?:is|should|can|does)|instead\b|the\s+question\s+is|the\s+point\s+is|"
    r"the\s+contribution\s+is|the\s+issue\s+is|the\s+problem\s+is|what\s+matters\s+is)",
    re.I,
)

SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9\(\[])" )

GENERIC_PIVOT = re.compile(
    r"\b(?:this\s+(?:highlights|reveals|underscores|demonstrates|illustrates|points\s+to)|"
    r"what\s+matters\s+is|the\s+key\s+point\s+is|more\s+broadly)\b",
    re.I,
)

def normalize_sentence_for_repetition(sentence: str) -> str:
    s = re.sub(r"[`*_#]+", "", sentence)
    s = re.sub(r"\s+", " ", s).strip().lower()
    s = re.sub(r"[.!?]+$", "", s)
    return s


def is_short_antithesis_pair(previous: str, current: str) -> bool:
    prev_words = re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", previous)
    cur_words = re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", current)
    if not (2 <= len(prev_words) <= 14 and 2 <= len(cur_words) <= 14):
        return False

    if NEGATIVE_REDEFINITION.search(previous) and POSITIVE_REDEFINITION_OPENING.search(current):
        return True

    if re.match(r"^\s*(?:but|yet|however|instead)\b", current, re.I):
        return True
    if re.match(r"^\s*what\s+may\s+be\s+missing\b", current, re.I):
        return True
    if re.match(r"^\s*it\s+(?:should|must|can|does)\s+not\b", current, re.I):
        return True

    if re.search(r"\b(?:is|are|was|were|does|do|did|can|could|should|must)\s+not\s*[.!?]*$", current, re.I):
        return True

    if re.search(r"\bnot\s+(?:the\s+)?(?:problem|issue|point)\b", previous, re.I):
        if re.search(r"\b(?:is|are)\b", current, re.I):
            return True

    return False


def sentence_chunks(line: str) -> list[str]:
    line = line.strip()
    if not line:
        return []
    return [s.strip() for s in SENTENCE_SPLIT.split(line) if s.strip()]


def logical_blocks(text: str) -> list[tuple[int, str]]:
    """Join soft-wrapped prose lines while preserving structural Markdown lines.

    This makes the linter less sensitive to whether a manuscript paragraph is
    stored as one long line or wrapped across several lines.
    """
    blocks: list[tuple[int, str]] = []
    current: list[str] = []
    current_start = 1
    in_code = False

    def flush() -> None:
        nonlocal current, current_start
        if current:
            blocks.append((current_start, " ".join(current).strip()))
            current = []

    for lineno, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()

        # Reference lists are bibliographic data, not manuscript prose. Stop the
        # style audit at a standalone references/bibliography heading.
        if re.sub(r"^[#\s]+", "", stripped).strip().lower() in {"references", "bibliography", "works cited"}:
            flush()
            break

        if stripped.startswith("```"):
            flush()
            in_code = not in_code
            continue
        if in_code:
            continue

        if not stripped:
            flush()
            continue

        structural = (
            stripped.startswith("#")
            or stripped.startswith("|")
            or re.match(r"^(?:[-*+]\s+|\d+[.)]\s+)", stripped) is not None
        )
        if structural:
            flush()
            continue

        if not current:
            current_start = lineno
        current.append(stripped)

    flush()
    return blocks


def protected(sentence: str) -> bool:
    return any(p.search(sentence) for p in PROTECTED_OPENINGS)


def analyse_with_metrics(text: str) -> tuple[list[Finding], dict[str, int | float]]:
    findings: list[Finding] = []
    sentence_openers: Counter[str] = Counter()
    paragraph_closures = 0
    contrast_positions: list[tuple[int, int, str]] = []  # (global sentence index, line, excerpt)
    meta_pivot_positions: list[tuple[int, int, str]] = []
    generic_pivot_positions: list[tuple[int, int, str]] = []
    redefinition_positions: list[tuple[int, int, str]] = []
    antithesis_pairs: list[tuple[int, int, str]] = []
    sentence_records: list[tuple[int, int, str, str]] = []  # index, line, sentence, normalized

    sentence_index = 0
    previous_sentence: str | None = None
    previous_line: int | None = None

    for lineno, block in logical_blocks(text):
        sentences = sentence_chunks(block)
        for sentence in sentences:
            sentence_index += 1
            words = re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", sentence)
            normalized = normalize_sentence_for_repetition(sentence)
            sentence_records.append((sentence_index, lineno, sentence, normalized))

            if words:
                opener = " ".join(w.lower() for w in words[:2])
                sentence_openers[opener] += 1

            if META_PIVOT.search(sentence):
                meta_pivot_positions.append((sentence_index, lineno, sentence[:220]))

            if GENERIC_PIVOT.search(sentence):
                generic_pivot_positions.append((sentence_index, lineno, sentence[:220]))

            # Count a negative redefinition only when the second sentence is
            # genuinely positive/reframing. A chain such as
            # "Policy does not... The problem is not... It is..." should not
            # create two overlapping pairs from one rhetorical move.
            current_is_positive_redefinition = (
                POSITIVE_REDEFINITION_OPENING.search(sentence)
                and not (
                    (m := NEGATIVE_REDEFINITION.search(sentence))
                    and m.start() < 80
                )
            )
            if previous_sentence and NEGATIVE_REDEFINITION.search(previous_sentence) and current_is_positive_redefinition:
                redefinition_positions.append(
                    (
                        sentence_index,
                        previous_line or lineno,
                        f"{previous_sentence[:105]} | {sentence[:105]}",
                    )
                )

            if previous_sentence and is_short_antithesis_pair(previous_sentence, sentence):
                antithesis_pairs.append(
                    (
                        sentence_index,
                        previous_line or lineno,
                        f"{previous_sentence[:105]} | {sentence[:105]}",
                    )
                )

            for rule, regex, severity, message in PATTERNS:
                if regex.search(sentence):
                    if rule == "pivot.generic" and protected(sentence) and not regex.search(sentence[40:]):
                        continue
                    findings.append(Finding(rule, severity, lineno, sentence[:220], message))
                    if rule == "contrast.not_but":
                        contrast_positions.append((sentence_index, lineno, sentence[:220]))

            # Very long sentences are review candidates, not errors.
            if len(words) >= 50:
                findings.append(
                    Finding(
                        "readability.long_sentence",
                        "low",
                        lineno,
                        sentence[:220],
                        f"Long sentence ({len(words)} words); review for clause overload, not length alone.",
                    )
                )

            # A short standalone line is only a review candidate when it uses an
            # explicit slogan-like cue. Bare modal verbs and diagnostic questions
            # are not enough: conceptual papers often need short questions,
            # definitions, and function-specific requirements.
            if len(sentences) == 1 and 3 <= len(words) <= 11 and not sentence.rstrip().endswith("?"):
                if re.search(
                    r"\b(?:the problem is|the point is|what matters is|the issue is|"
                    r"the distinction matters|is not the same as)\b",
                    sentence,
                    re.I,
                ):
                    findings.append(
                        Finding(
                            "pivot.short_standalone",
                            "low",
                            lineno,
                            sentence[:220],
                            "Short standalone conceptual pivot; keep if it carries necessary analysis rather than rhetorical staging.",
                        )
                    )

            previous_sentence = sentence
            previous_line = lineno

        if sentences and GENERIC_CLOSURES.search(sentences[-1]):
            paragraph_closures += 1

    total_sentences = sentence_index

    # Repeated opening patterns are only reported at fairly high density.
    if total_sentences >= 8:
        for opener, count in sentence_openers.items():
            if count >= 4 and count / max(total_sentences, 1) >= 0.18:
                findings.append(
                    Finding(
                        "repetition.sentence_opening",
                        "moderate",
                        0,
                        opener,
                        f"Sentence opening '{opener}' appears {count} times ({count/total_sentences:.0%} of sentences).",
                    )
                )

    if paragraph_closures >= 3:
        findings.append(
            Finding(
                "repetition.paragraph_closure",
                "moderate",
                0,
                "",
                f"Generic significance language appears at the end of {paragraph_closures} paragraphs.",
            )
        )

    # Detect local contrast clustering: three not/but patterns within any six-sentence window.
    cluster_count = 0
    for i in range(len(contrast_positions)):
        window = [p for p in contrast_positions[i:] if p[0] - contrast_positions[i][0] <= 5]
        if len(window) >= 3:
            cluster_count += 1
            lines_in_cluster = sorted({line for _, line, _ in window[:3]})
            excerpt = " || ".join(p[2] for p in window[:3])
            findings.append(
                Finding(
                    "repetition.contrast_cluster",
                    "moderate",
                    lines_in_cluster[0],
                    excerpt[:440],
                    "Three contrastive 'not X but Y' structures occur within a six-sentence window; review the cluster for over-engineered symmetry.",
                )
            )
            break

    # Conceptual papers often use explicit metadiscursive staging legitimately.
    # Review it only when several such pivots cluster locally.
    meta_cluster_count = 0
    for i in range(len(meta_pivot_positions)):
        window = [p for p in meta_pivot_positions[i:] if p[0] - meta_pivot_positions[i][0] <= 11]
        if len(window) >= 3:
            meta_cluster_count += 1
            lines_in_cluster = sorted({line for _, line, _ in window[:3]})
            excerpt = " || ".join(p[2] for p in window[:3])
            findings.append(
                Finding(
                    "repetition.metadiscursive_pivot_cluster",
                    "moderate",
                    lines_in_cluster[0],
                    excerpt[:440],
                    "Three or more conceptual staging pivots occur within a twelve-sentence window; review whether the distinctions can be stated more directly.",
                )
            )
            break

    # Generic pivots are low-level candidates in isolation. Escalate only when
    # they recur locally.
    generic_pivot_cluster_count = 0
    for i in range(len(generic_pivot_positions)):
        window = [p for p in generic_pivot_positions[i:] if p[0] - generic_pivot_positions[i][0] <= 19]
        if len(window) >= 3:
            generic_pivot_cluster_count += 1
            lines_in_cluster = sorted({line for _, line, _ in window[:3]})
            excerpt = " || ".join(p[2] for p in window[:3])
            findings.append(
                Finding(
                    "repetition.generic_pivot_cluster",
                    "moderate",
                    lines_in_cluster[0],
                    excerpt[:440],
                    "Three generic significance pivots occur within a twenty-sentence window; review whether repeated staging can be replaced by direct analytical claims.",
                )
            )
            break

    redefinition_cluster_count = 0
    for i in range(len(redefinition_positions)):
        first = redefinition_positions[i]
        # Pair endpoints one sentence apart share the middle sentence and are
        # therefore one chained redefinition, not two independent repetitions.
        later = [p for p in redefinition_positions[i + 1:] if 2 <= p[0] - first[0] <= 19]
        if later:
            window = [first, later[0]]
            redefinition_cluster_count += 1
            lines_in_cluster = sorted({line for _, line, _ in window})
            excerpt = " || ".join(p[2] for p in window)
            findings.append(
                Finding(
                    "repetition.negative_redefinition_pair",
                    "moderate",
                    lines_in_cluster[0],
                    excerpt[:440],
                    "Repeated non-overlapping 'not X. It is Y' style redefinitions occur within a twenty-sentence window; review for conceptual over-staging.",
                )
            )
            break

    # Repeated compact reversals can sound aphoristic even when no one pair is
    # objectionable. Escalate only at manuscript level when the pattern recurs.
    antithesis_cluster_count = 0
    if len(antithesis_pairs) >= 5:
        antithesis_cluster_count = 1
        excerpt = " || ".join(p[2] for p in antithesis_pairs[:3])
        findings.append(
            Finding(
                "repetition.short_antithesis_pairs",
                "moderate",
                antithesis_pairs[0][1],
                excerpt[:440],
                f"{len(antithesis_pairs)} compact contrastive sentence pairs were detected; review whether repeated aphoristic staging is carrying more emphasis than analysis.",
            )
        )

    # Exact sentence repetition is useful to surface because conceptual papers
    # often repeat diagnostic questions or slogans intentionally. Report it as
    # Low rather than treating repetition as an error.
    normalized_counts = Counter(
        norm
        for _, _, sentence, norm in sentence_records
        if 4 <= len(re.findall(r"\b[A-Za-z][A-Za-z'-]*\b", sentence)) <= 35 and norm
    )
    exact_repeat_count = 0
    for norm, count in normalized_counts.items():
        if count < 2:
            continue
        matches = [(idx, line, sentence) for idx, line, sentence, n in sentence_records if n == norm]
        if not matches:
            continue
        exact_repeat_count += 1
        findings.append(
            Finding(
                "repetition.exact_sentence",
                "low",
                matches[0][1],
                matches[0][2][:220],
                f"Exact sentence appears {count} times; repetition may be intentional, but review whether every recurrence adds value.",
            )
        )

    moderate_count = sum(f.severity == "moderate" for f in findings)
    low_count = sum(f.severity == "low" for f in findings)
    metrics: dict[str, int | float] = {
        "total_sentences": total_sentences,
        "moderate_findings": moderate_count,
        "low_findings": low_count,
        "moderate_density": moderate_count / max(total_sentences, 1),
        "low_density": low_count / max(total_sentences, 1),
        "contrast_clusters": cluster_count,
        "metadiscursive_pivots": len(meta_pivot_positions),
        "metadiscursive_pivot_clusters": meta_cluster_count,
        "generic_pivots": len(generic_pivot_positions),
        "generic_pivot_clusters": generic_pivot_cluster_count,
        "negative_redefinition_pairs": len(redefinition_positions),
        "negative_redefinition_clusters": redefinition_cluster_count,
        "short_antithesis_pairs": len(antithesis_pairs),
        "short_antithesis_clusters": antithesis_cluster_count,
        "exact_repeated_sentences": exact_repeat_count,
    }
    return findings, metrics

def analyse(text: str) -> list[Finding]:
    findings, _ = analyse_with_metrics(text)
    return findings


def risk_level(findings: Iterable[Finding], metrics: dict[str, int | float] | None = None) -> str:
    sev = Counter(f.severity for f in findings)
    if metrics is None:
        total = 0
        density = 0.0
        low_density = 0.0
        clusters = 0
    else:
        total = int(metrics.get("total_sentences", 0))
        density = float(metrics.get("moderate_density", 0.0))
        low_density = float(metrics.get("low_density", 0.0))
        clusters = (
            int(metrics.get("contrast_clusters", 0))
            + int(metrics.get("metadiscursive_pivot_clusters", 0))
            + int(metrics.get("generic_pivot_clusters", 0))
            + int(metrics.get("negative_redefinition_clusters", 0))
            + int(metrics.get("short_antithesis_clusters", 0))
        )

    # Density matters more than raw count. A long manuscript should not receive a
    # Moderate or High rating merely because a few legitimate academic constructions occur.
    # A local repetition cluster remains meaningful even when manuscript-wide density is low.
    if total >= 20 and sev["moderate"] >= 8 and density >= 0.08:
        return "High"
    if clusters >= 1:
        return "Moderate"
    if sev["moderate"] >= 2 and (total < 20 or density >= 0.02):
        return "Moderate"
    if sev["low"] >= 5 and (total < 20 or low_density >= 0.05):
        return "Moderate"
    return "Low"

def render_text(path: Path, findings: list[Finding], metrics: dict[str, int | float]) -> str:
    risk = risk_level(findings, metrics)
    out = [
        "PaperAudit static style report",
        "=" * 34,
        f"File: {path}",
        f"AI-style pattern risk: {risk}",
        f"Sentences reviewed: {metrics.get('total_sentences', 0)}",
        f"Moderate-pattern density: {float(metrics.get('moderate_density', 0.0)):.1%}",
        f"Low-pattern density: {float(metrics.get('low_density', 0.0)):.1%}",
        f"Metadiscursive pivots tracked: {metrics.get('metadiscursive_pivots', 0)}",
        f"Generic pivots tracked: {metrics.get('generic_pivots', 0)}",
        f"Negative-redefinition pairs tracked: {metrics.get('negative_redefinition_pairs', 0)}",
        f"Short antithesis pairs tracked: {metrics.get('short_antithesis_pairs', 0)}",
        f"Exact repeated sentences tracked: {metrics.get('exact_repeated_sentences', 0)}",
        "Note: this is not an AI-authorship probability.",
        "",
    ]
    if not findings:
        out.append("No configured style patterns were detected.")
        return "\n".join(out)

    for f in findings:
        where = f"line {f.line}" if f.line else "document level"
        out.append(f"[{f.severity.upper()}] {f.rule} ({where})")
        if f.excerpt:
            out.append(f"  {f.excerpt}")
        out.append(f"  {f.message}")
        out.append("")

    out.append("Interpret findings contextually. Conventional academic phrasing is not evidence of AI authorship.")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Conservative static style audit for academic prose")
    parser.add_argument("--version", action="version", version=f"PaperAudit {VERSION}")
    parser.add_argument("file", type=Path)
    parser.add_argument("--format", choices=["text", "json"], default="text")
    parser.add_argument("--strict", action="store_true", help="Exit 1 when high-priority style risks are present")
    args = parser.parse_args()

    try:
        text = args.file.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    findings, metrics = analyse_with_metrics(text)
    risk = risk_level(findings, metrics)

    if args.format == "json":
        payload = {
            "file": str(args.file),
            "ai_style_pattern_risk": risk,
            "authorship_inference": "not performed",
            "metrics": metrics,
            "findings": [asdict(f) for f in findings],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(render_text(args.file, findings, metrics))

    if args.strict and risk == "High":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
